# project_id must be first
project_id = "uubpxlhfkxqjrsgnwlzh"

[global]
maxDuration = 300

[[experimental.workflows]]
slug = "transcribe"
max_jobs = 10
version = "v0"

[[functions]]
name = "tiktok-apify-scraper"
verify_jwt = true