project_id = "uubpxlhfkxqjrsgnwlzh"

[global.env]
OPENAI_API_KEY = "env"
SUPABASE_URL = "env"
SUPABASE_ANON_KEY = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"
SUPABASE_DB_URL = "env"

[functions.transcribe]
verify_jwt = true

[functions.generate-variation]
verify_jwt = true