project_id = "uubpxlhfkxqjrsgnwlzh"

[functions.create-checkout-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.resume-subscription]
verify_jwt = true

[functions.update-subscription]
verify_jwt = true

[functions.instagram-scraper]
verify_jwt = true