[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force non-www to www
[[redirects]]
  from = "https://example.com/*"
  to = "https://www.example.com/:splat"
  status = 301
  force = true

# Also handle http
[[redirects]]
  from = "http://example.com/*"
  to = "https://www.example.com/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true